gpt support debugging

diff --git a/part2/stages/Functions/install-main b/part2/stages/Functions/install-main
--- a/part2/stages/Functions/install-main
+++ b/part2/stages/Functions/install-main
@@ -22,11 +22,12 @@ create_ext4_partition() {
     local SECONDARY_DISK=$1
     local SECONDARY_DISK_DEV="/dev/${SECONDARY_DISK}"
 
-    do_cmd sgdisk -N 1 "${SECONDARY_DISK_DEV}" >&2
+    # do_cmd sgdisk -N 1 "${SECONDARY_DISK_DEV}" >&2
+    do_cmd parted "${SECONDARY_DISK_DEV}" -- mkpart lvm 100 -1 >&2
 
     # Don't like the way I refer to /dev/sd*1 here, should be made more clear
-    do_cmd mkfs.ext4 -N 65536 -q "${SECONDARY_DISK_DEV}"1        >&2 || return 1
-    do_cmd tune2fs -i 0 -c -1 -m 0 "${SECONDARY_DISK_DEV}"1      >&2 || return 1
+    do_cmd mkfs.ext4 -N 65536 -q "${SECONDARY_DISK_DEV}"2        >&2 || return 1
+    do_cmd tune2fs -i 0 -c -1 -m 0 "${SECONDARY_DISK_DEV}"2      >&2 || return 1
 }
 
 format_secondary_disks() {
@@ -880,10 +881,11 @@ write_disk_gpt()
     if [ "${INSTALL_GPT}" = "true" ] ; then
         mixedgauge "Updating GPT..." 95
         local DISK_DEV="/dev/${TARGET_DISK}"
-        if ! do_cmd sgdisk -g "${DISK_DEV}" >&2 ; then
-            echo "ERROR: Failure installing the disk GPT: aborting.">&2
-            return 1
-        fi
+        #if ! do_cmd sgdisk -g "${DISK_DEV}" >&2 ; then
+        #if ! do_cmd parted -s "${DISK_DEV}" -- mktable gpt >&2 ; then
+        #    echo "ERROR: Failure installing the disk GPT: aborting.">&2
+        #    return 1
+        #fi
     fi
 
     return 0
